<?

function alias_suggestion_preprocess_page($vars, $hook) 
{
  // only do this for page-type nodes and only if Path module exists
  if (module_exists('path'))
  {
    // look up the alias from the url_alias table
	if(isset($vars['node']){
			$source = 'node/' . $vars['node']->nid;
	}
	if(isset($vars['taxonomy']) {
			$source = 'taxonomy/term/' .$vars['taxonomy']->tid;
	}
	
	if(!isset($source)) exit;
	
    $alias = db_query("SELECT alias FROM {url_alias} WHERE source = '$source'")->fetchField();

    if ($alias != '')
    {
      // build a suggestion for every possibility
      $parts = explode('/', $alias);
      $suggestion = '';
      foreach ($parts as $part)
      {
        if ($suggestion == '')
        {
          // first suggestion gets prefaced with 'page--'
          $suggestion .= "page--$part";
        }
        else
        {
          // subsequent suggestions get appended
          $suggestion .= "__$part";
        }
        // add the suggestion to the array
        $vars['theme_hook_suggestions'][] = $suggestion;
      }
    }
  }
}?>